export const viaRoadShortNames = [
  "Dar - Morogoro",
  "Dar - Morogoro - Iringa - Njombe - Mbeya",
  "Dar - Morogoro - Dodoma",
  "Dar - Morogoro - Mwanza",
  "Dar - Tanga",
  "Dar - Kigoma",
  "Dar - Morogoro - Dodoma - Tabora",
  "Dar - Morogoro - Dodoma - Tabora - Kigoma",
  "Dar - Morogoro - Dodoma - Singida",
  "Dar - Morogoro - Dodoma - Singida - Shinyanga",
  "Dar - Morogoro - Dodoma - Singida - Shinyanga - Geita - Kagera",
  "Dar - Morogoro - Dodoma - Singida - Shinyanga - Geita - Mara - Mwanza",
  "Dar - Morogoro - Dodoma - Singida - Shinyanga - Geita - Mara - Mwanza - Simiyu",
  "Dar - Morogoro - Dodoma - Singida - Shinyanga - Geita - Mara - Mwanza - Simiyu - Manyara - Babati",
  "Dar - Morogoro - Dodoma - Singida - Shinyanga - Geita - Mara - Mwanza - Simiyu - Manyara - Babati - Singida",
  "Dodoma - Singida",
  "Dodoma - Singida - Manyara - Babati - Arusha",
  "Dodoma - Singida - Manyara - Babati - Arusha - Moshi - Tanga",
  "Dodoma - Singida - Manyara - Babati - Arusha - Moshi - Pangani - Tanga",
  "Dodoma - Singida - Manyara - Babati - Arusha - Kilimanjaro",
  "Dodoma - Singida - Manyara - Babati - Arusha - Kilimanjaro - Tabora",
  "Dodoma - Singida - Manyara - Babati - Arusha - Kilimanjaro - Tabora - Kigoma",
  "Dodoma - Singida - Manyara - Babati - Arusha - Kilimanjaro - Tabora - Kigoma - Mwanza",
  "Dodoma - Singida - Manyara - Babati - Arusha - Kilimanjaro - Tabora - Kigoma - Mwanza - Shinyanga",
  "Mwanza - Shinyanga",
  "Mwanza - Shinyanga - Geita",
  "Mwanza - Shinyanga - Geita - Mara",
  "Mwanza - Shinyanga - Geita - Mara - Simiyu",
  "Mwanza - Shinyanga - Geita - Mara - Simiyu - Kagera",
  "Mwanza - Shinyanga - Geita - Mara - Simiyu - Kagera - Kigoma",
  "Mwanza - Shinyanga - Geita - Mara - Simiyu - Kagera - Kigoma - Tabora",
  "Mwanza - Shinyanga - Geita - Mara - Simiyu - Kagera - Kigoma - Tabora - Singida",
  "Mwanza - Shinyanga - Geita - Mara - Simiyu - Kagera - Kigoma - Tabora - Singida - Dodoma",
];
